ENG-4176: added precise error location info when validating descriptor
entando/entando-bundle-cli pull request #131
Opened 2022-12-02 09:35 UTC by antromeo

2022-12-02 10:01 UTC, cecchisandrone commented on src/services/bundle-descriptor-service.ts
> +  private parseData(descriptorFileContent: string): any {
parseDescriptor

2022-12-02 10:42 UTC, cecchisandrone approved these changes

2022-12-14 10:07 UTC, zonia3000 approved these changes

2022-12-14 10:10 UTC, alepintus requested changes

2022-12-14 10:10 UTC, alepintus commented on test/services/bundle-descriptor-service.test.ts
> +  const mocks = [
I think we could move this mock in the folder `test/helpers/mocks`. WDYT?

2022-12-14 11:25 UTC, alepintus approved these changes

2022-12-15 13:12 UTC, merged