ENG-5026 plugin error handling
entando/entando-bundle-cli pull request #181
Opened 2023-07-03 14:34 UTC by antromeo

Wait for ENG-5006

2023-07-04 14:19 UTC, avdev4j requested changes

2023-07-04 14:19 UTC, avdev4j commented on src/commands/convert.ts
>  const MANUALLY_STEPS_DESCRIPTION = 'MANUALLY STEPS TO DO'
```suggestion
const MANUAL_STEPS_DESCRIPTION = 'MANUAL STEPS TO DO'
```

2023-07-04 14:19 UTC, avdev4j commented on src/commands/convert.ts
> +const MANUALLY_STEPS = [
```suggestion
const MANUAL_STEPS = [
```

2023-07-04 14:19 UTC, avdev4j commented on src/commands/convert.ts
> +  `\n${MANUALLY_STEPS_DESCRIPTION}\n`,
```suggestion
  `\n${MANUAL_STEPS_DESCRIPTION}\n`,
```

2023-07-04 14:19 UTC, avdev4j commented on src/commands/convert.ts
> +    register.push(...MANUALLY_STEPS)
```suggestion
    register.push(...MANUAL_STEPS)
```

2023-07-04 14:22 UTC, avdev4j commented
I tried to remove the plugin descriptor in my tested project (v1 bundle) but keep the entry in the main descriptor and no errors have been raised. Also, the output messages in the console don't match the examples included in the ticket

2023-07-04 15:50 UTC, antromeo commented
> I tried to remove the plugin descriptor in my tested project (v1 bundle) but keep the entry in the main descriptor and no errors have been raised. Also, the output messages in the console don't match the examples included in the ticket. Any idea @antromeo ?
yes, the tool shouldn't break, if there is a plugin with a processing error, only the plugin with error will be skipped.
if you want to see more details in the console, you need to enable debug mode or check the log file

2023-07-05 12:45 UTC, avdev4j approved these changes

2023-07-05 14:51 UTC, merged