ENG-3701 Added parallel process executor
entando/entando-bundle-cli pull request #23
Opened 2022-05-25 10:22 UTC by zonia3000

2022-05-25 14:33 UTC, cecchisandrone commented on src/services/fs-service.ts
> +    FSService.debug("checking bundle name if it's accepted")
checking if bundle name is valid

2022-05-25 14:33 UTC, cecchisandrone commented on src/services/process-executor-service.ts
> +const PARALLELISM = 2
DEFAULT_PARALLEL_PROCESSES_SIZE

2022-05-25 14:33 UTC, cecchisandrone commented on src/services/process-executor-service.ts
>    command: string
specify what is the default for workDir if not specified

2022-05-25 14:33 UTC, cecchisandrone commented on src/services/process-executor-service.ts
> + * Executes multiple long running child processes and handles their output streams.
I would add a note regarding the execution order

2022-05-25 16:26 UTC, raxkaynan requested changes
Just minor changes

2022-05-25 16:26 UTC, raxkaynan commented on src/services/process-executor-service.ts
> +      // reversing queue, so that when we use pop() the first process of the list
`shift()` can be used to avoid having to reverse the array

2022-05-25 16:26 UTC, raxkaynan commented on src/services/process-executor-service.ts
> +          reject(new ExecutionError(code === null ? signal! : code))
You could also write `code ?? signal!` if you prefer it to be shorter :)
Same with [this line](https://github.com/entando/entando-bundle-cli/pull/23/files#diff-0d111d424524e7084e39844946aea6238e47d3198f4de8dbbf2fdaba1d361518R148)

2022-05-25 16:49 UTC, cecchisandrone approved these changes

2022-05-26 07:14 UTC, zonia3000 commented on src/services/process-executor-service.ts
> +      // reversing queue, so that when we use pop() the first process of the list
thanks, much better!

2022-05-26 07:33 UTC, merged