ENG-3598 Package command implementation
entando/entando-bundle-cli pull request #26
Opened 2022-05-27 15:05 UTC by zonia3000

In addition to package command implementation, I refactored some parts of the code:

* I split the `Stack` enum in `MicroFrontendStack` e `MicroServiceStack` and I defined a `StackFor<T extends ComponentType>` type that is used to avoid that a MFE stack can be assigned to a MS and vice-versa. This is needed for correctly defining the `CommandsDefinition` type, which is used by the command factory to dynamically obtain the commands to build/package a component.
* I changed the promise of `ProcessExecutorService` to resolve always, as happens in the parallel version, so we can avoid to catch the exception in the command in order to display a proper error message
* I created a `BaseBuildCommand` that can be used by build, build-all and package commands, since it contains some methods for handling execution of commands on a set of components

2022-05-30 06:39 UTC, raxkaynan requested changes

2022-05-30 06:39 UTC, raxkaynan commented on src/services/microfrontend-service.ts
> +    fs.rmSync(mfedir, { recursive: true, force: true })
I think it's safe to remove `force: true` here.

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/base-build.ts
> +export abstract class BaseBuildCommand extends Command {
This is appearing in the command help, it should be hidden

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/build.ts
> +        console.error(`Build failed, exit with code ${result}`)
replace console.error() with this.error()

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/base-build.ts
> +  ) {
missing return type?

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/base-build.ts
> +    this.log('Building packages...')
Building components...

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/build.ts
>    static description = 'Build the component'
Build bundle components

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/base-build.ts
> +  public checkBuildResults(
should this be `private`?

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +      ? await CliUx.ux.confirm('Rebuild components?')
Do you want to rebuild all bundle components?

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +      bundleDescriptor.version
Docker images for MS will get their component version, not the bundle version

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +      description: 'Name of the Dockerfile (default is Dockerfile)',
Bundle Dockerfile (default is Dockerfile)

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +      ? await CliUx.ux.confirm('Rebuild components?')
Let's remove this as per the comment above

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +  private async buildMicroServicesDockerImages(
I would check for Dockerfile before calling the docker command and fail silently with it. In this way we can give a more explicit error like "Dockerfile not found for microservice <abc>. Please provide one in order to proceed with the bundle packaging"

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +    this.log('Building microservices Docker images...')
Probably better to colorize macro steps or make it more visible (------ Building ... ----) in order to be more evident in the logs

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/base-build.ts
> +      let errorMessage = 'Following components failed to build:\n'
The following components failed to build:\n

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +    file: Flags.string({
Let's modify a bit the UX. Add a flag -b to build all the components. If missing build will not be invoked

2022-05-30 08:25 UTC, cecchisandrone commented on src/commands/package.ts
> +    CliUx.ux.action.start('Creating bundle package')
Let's also log the full bundle image name at the end

2022-05-31 08:18 UTC, cecchisandrone approved these changes

2022-05-31 08:22 UTC, merged